[phases.setup]
nixPkgs = ["nodejs_24", "pnpm"]

[phases.install]
cmds = ["corepack enable", "pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm run build:railway"]

[start]
cmd = "pnpm run start"