packages:
  - "artifacts/*"
  - "lib/*"
  - "lib/integrations/*"
  - "scripts"

catalog:
  '@types/node': ^25.3.3
  '@types/react': ^19.2.0
  '@types/react-dom': ^19.2.0
  '@replit/vite-plugin-cartographer': '*'
  '@replit/vite-plugin-dev-banner': '*'
  '@replit/vite-plugin-runtime-error-modal': '*'
  '@tailwindcss/vite': ^4.1.8
  '@tanstack/react-query': ^5.90.21
  '@vitejs/plugin-react': ^4.5.2
  'class-variance-authority': ^0.7.1
  'clsx': ^2.1.1
  'drizzle-orm': ^0.44.1
  'framer-motion': ^12.19.0
  'lucide-react': ^0.517.0
  'react': 19.1.0
  'react-dom': 19.1.0
  'tailwind-merge': ^3.3.1
  'tailwindcss': ^4.1.8
  'vite': ^7.3.2
  'zod': ^3.25.67

autoInstallPeers: false